version: '3.8'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: supersecreto
      MARIADB_DATABASE: green_house_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=supersecreto
      - DB_PORT=3306
      - DB_NAME=green_house_db
      - JWT_SECRET=YTG2il5kFnVPiT0Okq6bYSVQ88k6qAg09ndQCEEkerC
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: